// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iejpsvwhbvhprpmyfwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllanBzdndoYnZocHJwbXlmd2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTYyMzQsImV4cCI6MjA2MjI5MjIzNH0.XRCVCG958fGlNbfWI_hjqapsTzz2gI2O_eHdnjYFbL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);